### ISSUE TITLE
OSError: Google Drive quota exceeded

### ISSUE THREAD

**Issue by paramoza999** [tg-bomze/Face-Depixelizer#14]
always shows this error even though i keep trying at different times

**Comment by ruchirshetye** [comment]
Yup, same issue on my end. Here the Error which is thrown after uploading the image:

Estimated Runtime: 29s.

```
Loading Synthesis Network
Downloading https://drive.google.com/uc?id=1TCViX1YpQyRsklTVYEJwdbmK91vklCo8 ............ failed
Traceback (most recent call last):
  File "run.py", line 58, in <module>
    model = PULSE(cache_dir=kwargs["cache_dir"])
  File "/content/pulse/PULSE.py", line 23, in __init__
    with open_url("https://drive.google.com/uc?id=1TCViX1YpQyRsklTVYEJwdbmK91vklCo8", cache_dir=cache_dir, verbose=verbose) as f:
  File "/content/pulse/drive.py", line 66, in open_url
    raise IOError("Google Drive quota exceeded")
OSError: Google Drive quota exceeded
```

**Comment by ruchirshetye** [comment]
Similar to #10
