### ISSUE TITLE
OSError: Google Drive quota exceeded

### ISSUE THREAD

**Issue by CatoLynx** [tg-bomze/Face-Depixelizer#8]
For three days now, I have not been able to get it to work on Colab.
Every time, I upload an image, that succeeds, then it tries to download something from a Google Drive link and I get this output:

```
Estimated Runtime: 29s.

Loading Synthesis Network
Downloading https://drive.google.com/uc?id=1TCViX1YpQyRsklTVYEJwdbmK91vklCo8 ............ failed
Traceback (most recent call last):
  File "run.py", line 58, in <module>
    model = PULSE(cache_dir=kwargs["cache_dir"])
  File "/content/pulse/PULSE.py", line 23, in __init__
    with open_url("https://drive.google.com/uc?id=1TCViX1YpQyRsklTVYEJwdbmK91vklCo8", cache_dir=cache_dir, verbose=verbose) as f:
  File "/content/pulse/drive.py", line 66, in open_url
    raise IOError("Google Drive quota exceeded")
OSError: Google Drive quota exceeded
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-af0d780e3ec8> in <module>()
     90 ax1.imshow(mpimg.imread('/content/pulse/input/face.png'))
     91 ax1.set_title('Original')
---> 92 ax2.imshow(mpimg.imread('/content/pulse/runs/face.png'))
     93 ax2.set_title('Result')
     94 plt.show()

3 frames
/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py in to_filehandle(fname, flag, return_opened, encoding)
    401             fh = bz2.BZ2File(fname, flag)
    402         else:
--> 403             fh = open(fname, flag, encoding=encoding)
    404         opened = True
    405     elif hasattr(fname, 'seek'):

FileNotFoundError: [Errno 2] No such file or directory: '/content/pulse/runs/face.png'
```

I would really love to try it out, but sadly I can't. Could you look into that please?

**Comment by woctezuma** [comment]
https://github.com/adamian98/pulse/issues/5

**Comment by CatoLynx** [comment]
Oh, I see. That sucks. Is there any way I could run this locally?

**Comment by Acurisu** [comment]
See https://github.com/tg-bomze/Face-Depixelizer/issues/10#issuecomment-648159788
